Resources:
  WebAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening up HTTP and SSH port.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 10.0.0.0/8
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
    LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening up HTTP and SSH port.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
    MongoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening up Mongo and SSH port.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '27017'
        ToPort: '27017'
        CidrIp: 10.0.0.0/8
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  WebApp1:
    Type: AWS::EC2::Instance
    Description: Launching Web App 1.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref WebAppSG
      UserData: !Base64 |
       #!/bin/bash
       yum update -y
       sudo su
       yum install golang -y
       export MONGODB_URL mongodb://admin:admin@HOST:27017/admin
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       chmod +x app.sh
       nohup ./app.sh &
  WebApp2:
    Type: AWS::EC2::Instance
    Description: Launching Web App 2.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref WebAppSG
      UserData: !Base64 |
       #!/bin/bash
       yum update -y
       sudo su
       yum install golang -y
       export MONGODB_URL mongodb://admin:admin@HOST:27017/admin
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       chmod +x app.sh
       nohup ./app.sh &
  LoadBalancer:
    Type: AWS::EC2::Instance
    Description: Launching Load Balancer.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref LoadBalancerSG
      UserData: !Base64 |
       #!/bin/bash
       yum update -y
       yum install epel-release -y
       yum install nginx -y
       chkconfig nginx
       service nginx start
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       cp load_balancer.conf /etc/nginx/conf.d/
  MongoMaster:
    Type: AWS::EC2::Instance
    Description: Launching Mongo Master.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref MongoSG
      UserData: !Base64 |
       #!/bin/bash
       wget https://repo.mongodb.org/yum/amazon/mongodb-org-3.1.repo -P /etc/yum.repos.d/
       yum update -y
       yum install -y mongodb-org
       service mongod start
       chkconfig mongod on
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       chmod +x mongo.sh
       bash ./mongo.sh
  MongoSecondary1:
    Type: AWS::EC2::Instance
    Description: Launching Mongo Secondary 1.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref MongoSG
      UserData: !Base64 |
       #!/bin/bash
       wget https://repo.mongodb.org/yum/amazon/mongodb-org-3.1.repo -P /etc/yum.repos.d/
       yum update -y
       yum install -y mongodb-org
       service mongod start
       chkconfig mongod on
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       chmod +x mongo.sh
       bash ./mongo.sh
  MongoSecondary2:
    Type: AWS::EC2::Instance
    Description: Launching Mongo Secondary 2.
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05868579
      KeyName: ec2-keypair
      SecurityGroups:
        - !Ref MongoSG
      UserData: !Base64 |
       #!/bin/bash
       wget https://repo.mongodb.org/yum/amazon/mongodb-org-3.1.repo -P /etc/yum.repos.d/
       yum update -y
       yum install -y mongodb-org
       service mongod start
       chkconfig mongod on
       yum install git -y
       git clone https://github.com/arifurreza/DevOps-Coding-Challenge.git
       cd DevOps-Coding-Challenge/
       chmod +x mongo.sh
       bash ./mongo.sh
